# /amft-project/configs/base/model_qwen7b.yaml


model_name_or_path: "Qwen/Qwen2.5-7B-Math"
tokenizer_name_or_path: "Qwen/Qwen2.5-7B-Math"
torch_dtype: "bfloat16"
trust_remote_code: true

model_revision: "main"